apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-api
  namespace: orbitcloud
  labels:
    app: orbit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-api
  template:
    metadata:
      labels:
        app: orbit-api
    spec:
      containers:
      - name: orbit-api-container
        image: localhost:5000/orbit-api:v1.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-api
  namespace: orbitcloud
spec:
  selector:
    app: orbit-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbit-api-ingress
  namespace: orbitcloud
  annotations:
    # Esta anotação garante que ele escute na porta segura
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.orbitcloud.com.br
      # Podemos deixar um nome de secret qualquer aqui. 
      # O Traefik vai usar um certificado padrão auto-assinado se não achar,
      # e a Cloudflare vai aceitar por causa do "No TLS Verify".
      secretName: orbitnet-default-cert 
  rules:
    - host: api.orbitcloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbit-api
                port:
                  number: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orbit-api-admin-binding
subjects:
  - kind: ServiceAccount
    name: default          # Nome da conta (padrão)
    namespace: orbitcloud  # O namespace onde sua API roda (CONFIRA SE É ESSE MESMO)
roleRef:
  kind: ClusterRole
  name: cluster-admin      # Permissão total no cluster inteiro
  apiGroup: rbac.authorization.k8s.io