apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-checker-job
  namespace: orbitcloud
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ip-checker-container
            image: alpine/curl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "Iniciando consulta...";

                # 1. Executa o curl (com retry, fail, e silent) e salva a saída.
                RESPONSE=$(curl --fail --retry 5 -s -X GET http://api-orbitnet-service:7002/api/v1/get-ip);

                # 2. Captura o código de saída do comando curl.
                EXIT_CODE=$?

                # 3. Imprime a Resposta e o Código de Saída para o Log do K8s
                echo "--- STATUS DA CONSULTA ---"
                echo "RESPONSE: $RESPONSE"
                echo "CURL EXIT CODE: $EXIT_CODE"

                # 4. Se o código for diferente de 0, forçamos o Pod a retornar o erro
                if [ $EXIT_CODE -ne 0 ]; then
                  echo "ERRO: A consulta falhou. Código de saída do curl foi: $EXIT_CODE";
                  exit $EXIT_CODE
                fi
                echo "Consulta concluída com sucesso (EXIT CODE 0).";
          restartPolicy: OnFailure