apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitnet-api
  namespace: orbitcloud
  labels:
    app: orbitnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitnet-api
  template:
    metadata:
      labels:
        app: orbitnet-api
    spec:
      containers:
      - name: orbitnet-api-container
        image: localhost:5000/orbitnet-api:v1.08
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orbitnet-api
  namespace: orbitcloud
spec:
  selector:
    app: orbitnet-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbitnet-api-ingress
  namespace: orbitcloud
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.orbitnet.crion.dev
      secretName: orbitnet-api-tls 
  rules:
    - host: api.orbitnet.crion.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbitnet-api
                port:
                  number: 8080