apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-ui
  namespace: orbitcloud
  labels:
    app: orbit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-ui
  template:
    metadata:
      labels:
        app: orbit-ui
    spec:
      containers:
      - name: orbit-ui-container
        image: localhost:5000/orbit-ui:v1.0.5
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-ui
  namespace: orbitcloud
spec:
  selector:
    app: orbit-ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbit-ui-ingress
  namespace: orbitcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - orbitcloud.com.br
      secretName: orbitnet-default-cert 
  rules:
    - host: orbitcloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbit-ui
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbit-admin-ui-ingress
  namespace: orbitcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - admin.orbitcloud.com.br
      secretName: orbitnet-default-cert 
  rules:
    - host: admin.orbitcloud.com.br
      http:
        paths:
          - path: /storage
            pathType: Prefix
            backend:
              service:
                name: orbit-ui
                port:
                  number: 3000