apiVersion: v1
kind: ConfigMap
metadata:
  namespace: orbitcloud
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: orbitcloud
  POSTGRES_USER: orbit
  POSTGRES_PASSWORD: 0rb1t!@#$
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: orbitcloud
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: cloudflare-r2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/orbit-r2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: orbitcloud
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: cloudflare-r2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orbitcloud
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              subPath: pgdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: orbitcloud
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

# kubectl run psql-client --rm -it --image=postgres --namespace orbitcloud -- bash
# psql -h postgres.orbitcloud.svc.cluster.local -U orbit -d orbitcloud

# kubectl run redis-client --rm -it --image=redis --namespace orbitcloud -- bash
# redis-cli -h redis-master
# AUHT mIpkRphicN