apiVersion: v1
kind: Secret # Trocado de ConfigMap para Secret por segurança
metadata:
  namespace: orbitcloud
  name: postgres-secret
type: Opaque
stringData: # Use stringData para não precisar converter pra base64 manualmente
  POSTGRES_DB: orbitcloud
  POSTGRES_USER: orbit
  POSTGRES_PASSWORD: "0rb1t!@#$"
---
# Removido o PersistentVolume manual para deixar a StorageClass trabalhar
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: orbitcloud
  name: postgres-volume-claim
spec:
  storageClassName: cloudflare-r2 # Aqui ele vai chamar o driver do R2
  accessModes:
    - ReadWriteMany # R2 permite isso, mas o Postgres precisa de cuidado
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orbitcloud
  name: postgres
spec:
  replicas: 1 # MANTENHA EM 1 para evitar corrupção de dados
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          envFrom:
            - secretRef: # Trocado para secretRef
                name: postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              # DICA: Postgres no S3/R2 às vezes exige um subPath para permissões
              subPath: pgdata 
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: orbitcloud
  name: postgres
spec:
  type: ClusterIP # Use ClusterIP para segurança interna, mude para NodePort só se precisar acessar de fora do cluster
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres