apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitsender-api
  namespace: orbitcloud
  labels:
    app: orbitsender-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitsender-api
  template:
    metadata:
      labels:
        app: orbitsender-api
    spec:
      containers:
      - name: orbitsender-api-container
        image: localhost:5000/orbitsender-api:v1.11
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orbitsender-api
  namespace: orbitcloud
spec:
  selector:
    app: orbitsender-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP